### ISSUE TITLE
Talk sur l'API

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro_v2#4]
Salut Tom, 

j'espère que tu vas bien à Paris!!

Je vais bientôt commencer à travailler sur deux nouveaux projets IT: 1) Site pour le ranking et 2) l'API.

Notamment sur l'API j'aimerais bien avoir un petit entretien skype avec toi pour mieux comprendre comment approcher cette démarche: temps à calculer pour travail, nécessité d'avoir un support IT, documentation là-dessus pour mieux comprendre quoi faire, etc. 

T'es dispo cette semaine pour 30-40 min au telephone? Aussi, j'aimerais bien qu'on fasse le point sur le temps que t'as jusqu'á present passé pour m'aider et te demander que tu nous fasse une première facture si tu veux. 

Ciao,
Nico

P.s. Je commence à me rendre compte que mon role IT, devrait être et devient en fait de project manager, et moins probablement de developper dés details CSS, etc. Interessant...

**Comment by thaume** [comment]
Hello Nico,

La date qui m'arrange le plus serait mardi prochain à 11h30 ou 12h.

En attendant tu peux lire cet article : https://labs.kollegorna.se/blog/2015/04/build-an-api-now/

Ta réflexion sur ton rôle est exactement celle que je te décrivais au départ : a good tech project manager gotta know its coding ;)

Cheers !
Tom

**Comment by NicholasWenzel** [comment]
Hello Tom,

top, mardi rendez-vous! Tête à tête. ;-D

Bon weekend,
Nico

2017-03-02 18:49 GMT+01:00 Tom Coquereau <notifications@github.com>:
