### ISSUE TITLE
Migration des donnés

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro_v2#5]
Salut Tom, 

j'aimerais bien faire la migration des 400 notations de notre ancien site web sur le nouveau projet Ruby. J'ai reçu la DUMP (en format .sql) de notre developer IT, ainsi que l'access au code source de l'ancien site. 

Peux-tu me guider sur ou regarder pour migrer les données et combien de temps cela pourrais prendre?

Merci,
Nico

**Comment by thaume** [comment]
Hello Nico,

Peux-tu me partager le dump par email ?
