### ISSUE TITLE
Approche pour le creation du review form comme discuté aujourd'hui

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro_v2#6]
Salut Tom, 

je veux tempter de créer le review form avec a) la possibilité de enregistrer deux fois, après la premiere page (stars page) quand on click "continue" et après la deuxième page (details page) quand on click "submit". 

Pour la démarche, est-ce que ceci est bon: 

- Create a MVC for the stars page.
- Create a MVC for the details page
- Create relations between the models
- Make sure you can click “Back” and details page and retrieve and change information from stars page
- Install Coocon Gem and create subquestions for one star-question

**Comment by NicholasWenzel** [comment]
Salut Tom, 

J'ai expérimenté avec la création de deux models. J'essaye de connecter deux models, Ranking model & Review model. 

1) Dans le Ranking controller, j'ai fait: 

def create
  @ranking = Ranking.new(ranking_params)
  if @ranking.save
    flash[:notice] = "Project has been created."
    redirect_to :controller => 'reviews', :action => 'new'
  else
    # nothing, yet
  end
end

Ceci me directe vers le controller reviews avec action new: 

  def new
    @review = Review.new
  end

Jusqu'ici tout est bien. Or, imaginons que quelqu'un veux retourner à la premiere page, après aver été redirecté sur la page the reviews/new pour modifier le contenu du forme dans Ranking. **Comment faire pour afficher les données?** D'habitude on travaillerai avec 

def edit
      @review = Review.find(params[:id])
    end

Mais ici, je pense que ca ne marche pas. T'as une idée? Ou c'est la mauvais approche?

**Comment by thaume** [comment]
Hello Nico,

Do not hesitate to switch to english if it is easier. 100% of my work happens in english right now ;)

**Create + edit**
I think you approach is the right one. The idea is that if someone is redirected to the "new" page, he should face a blank form everytime. This way, he has to go to the "edit" page if he wants to update a specific ranking.

The best of both world would be to automatically redirect him to the "show" view (from which he could click on an "edit" link that would push him to the "edit" route).

The flow would be as follow :
1/ "ranking/new" => creation of ranking
2/ "review/new" => creation of the review attached to the ranking model (through a one-to-one relationship).
3/ "review/:id" (auto redirection from 2/) => display the full review, from which the user can edit stuff if he wants to (with links "edit ranking" => ranking/:id/edit + "edit review" => review/:id/edit).

How does that sound ?

Cheers,
Tom

**Comment by NicholasWenzel** [comment]
Thanks, Tom! 

I'll look into that soon.
