### ISSUE TITLE
Urls .jobs

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro_v2#7]
Salut TOM, 

nous considérons d'acheter un site avec l'url .jobs. Est-ce qu'il y a des désavantages qui font de ca une mauvais idée, comme par example positionnement dans SEO? Cette URL devrais devenir l'URL principale que nous utiliserons. 

Merci,
Nico

**Comment by thaume** [comment]
Non tu peux y aller ;)
