### ISSUE TITLE
Finding a unique_id to connect our database with various job sites

### ISSUE THREAD

**Issue by NicholasWenzel** [NicholasWenzel/internsgopro_v2#8]
Salut Tom, 

Comment-va tu? En fin, on a une journée mi-chaude à Berlin avec du soleil! C’est bien ca, le 11 May! J’espere que tu se passe classe chez toi à Paris. 

Je t’ecris pour avoir ton avis sur une question IT. Avec nos developpeurs, qui font un bon travail jusqu’à maintenant on à un challenge technologique. Et j’aimerais bien voir tes idées la-dessus! Je te le descris en anglais. 

We are currently developing the widget that will connect our database with the partner job portals. The functionality is: 

**Functionality Need**
Thanks to our widget each job offer should display: 

1) a clickable summary of the ratings of the employer on our database. If you click on the link, the employer profile from our database with the reviews should appear (view  screenshot for visualization). 
![screen shot 2017-05-11 at 17 16 33](https://cloud.githubusercontent.com/assets/17838149/25957081/bdb8e26a-366d-11e7-8dee-46c731066ae4.png)
![screen shot 2017-05-11 at 17 16 27](https://cloud.githubusercontent.com/assets/17838149/25957079/bd2b41e4-366d-11e7-896c-6fc0a31db245.png)

2) Our label should appear if the employer has been certified by InternsGopro. 

**Our need**
-	Make sure our database and the partners job portals can communicate with each other, by recognizing the employers through a unique ID with the same name. 
-	The unique Id should be shared by all partners. 

**Our challenge**
-	Find a unique Id that all partners can use or might have? 

We were thinking of using the V.A.T of a company as a unique ID. Problem: Not all partners would have the V.A.T.

Do you bright, brilliant surprising ideas? Monday at 2.30 pm I'll have a talk with the developers. Will see what we come up with. ;-D

Chers,
Nico

**Comment by thaume** [comment]
You could try the D-U-N-S number ? Every company has its own I think

**Comment by NicholasWenzel** [comment]
Thanks, Maestro! On it, will keep you updated. 

Cheers,
Nik
